### ISSUE TITLE
Crashes on iOS 8 due to constraint error

### ISSUE THREAD

**Issue by jefflen** [RoleModel/RMSTokenView#12]
Fatal Exception: NSInternalInconsistencyException
Impossible to set up layout with view hierarchy unprepared for constraint.

Thread : Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x0000000185ae2084 __exceptionPreprocess + 132
1  libobjc.A.dylib                0x00000001965340e4 objc_exception_throw + 60
2  CoreFoundation                 0x0000000185ae1f44 +[NSException raise:format:]
3  Foundation                     0x0000000186961f54 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112
4  UIKit                          0x000000018a91a0e4 __120-[UIView(UIConstraintBasedLayout) _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:]_block_invoke_2 + 200
5  UIKit                          0x000000018a35ac38 -[UIView(UIConstraintBasedLayout) _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:] + 424
6  UIKit                          0x000000018a35aa4c -[UIView(UIConstraintBasedLayout) _tryToAddConstraintWithoutUpdatingConstraintsArray:roundingAdjustment:mutuallyExclusiveConstraints:] + 40
7  UIKit                          0x000000018a35a988 -[UIView(UIConstraintBasedLayout) _tryToAddConstraint:roundingAdjustment:mutuallyExclusiveConstraints:] + 292
8  UIKit                          0x000000018a364228 __50-[UIView(UIConstraintBasedLayout) addConstraints:]_block_invoke + 192
9  UIKit                          0x000000018a364154 -[UIView(UIConstraintBasedLayout) addConstraints:] + 292
10 TestApp                        0x00000001000bc2dc -[RMSTokenConstraintManager updateConstraintsForTokenLines:andLineView:withTextFieldFocus:isSearching:] (RMSTokenConstraintManager.m:120)
11 TestApp                        0x00000001000bf1cc -[RMSTokenView updateConstraints] (RMSTokenView.m:369)
12 UIKit                          0x000000018a91f5d0 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 252
13 UIKit                          0x000000018a91f7e0 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 136
14 CoreFoundation                 0x00000001859c506c CFArrayApplyFunction + 68
15 UIKit                          0x000000018a91f570 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 156
16 UIKit                          0x000000018a91f7e0 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 136
17 CoreFoundation                 0x00000001859c506c CFArrayApplyFunction + 68
18 UIKit                          0x000000018a91f570 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 156
19 UIKit                          0x000000018a91f7e0 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 136
20 CoreFoundation                 0x00000001859c506c CFArrayApplyFunction + 68
21 UIKit                          0x000000018a91f570 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 156
22 UIKit                          0x000000018a91f7e0 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 136
23 CoreFoundation                 0x00000001859c506c CFArrayApplyFunction + 68
24 UIKit                          0x000000018a91f570 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 156
25 UIKit                          0x000000018a91f7e0 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 136
26 CoreFoundation                 0x00000001859c506c CFArrayApplyFunction + 68
27 UIKit                          0x000000018a91f570 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 156
28 UIKit                          0x000000018a91f7e0 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 136
29 CoreFoundation                 0x00000001859c506c CFArrayApplyFunction + 68
30 UIKit                          0x000000018a91f570 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 156
31 UIKit                          0x000000018a91f7e0 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 136
32 CoreFoundation                 0x00000001859c506c CFArrayApplyFunction + 68
33 UIKit                          0x000000018a91f570 -[UIView(AdditionalLayoutSupport) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 156
34 UIKit                          0x000000018a91f7e0 -[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:] + 136
35 UIKit                          0x000000018a35ee88 __60-[UIView(AdditionalLayoutSupport) updateConstraintsIfNeeded]_block_invoke + 104
36 Foundation                     0x000000018690e368 -[NSISEngine withBehaviors:performModifications:] + 176
37 UIKit                          0x000000018a35eba4 -[UIView(AdditionalLayoutSupport) updateConstraintsIfNeeded] + 212
38 UIKit                          0x000000018a37b6a4 -[UIWindow(UIConstraintBasedLayout) updateConstraintsIfNeeded] + 104
39 UIKit                          0x000000018a91fb60 -[UIView(AdditionalLayoutSupport) _updateConstraintsAtEngineLevelIfNeeded] + 192
40 UIKit                          0x000000018a275d50 -[UIView(Hierarchy) layoutBelowIfNeeded] + 588
41 TestApp                        0x00000001000bfe60 __41-[RMSTokenView textFieldDidBeginEditing:]_block_invoke (RMSTokenView.m:471)
42 UIKit                          0x000000018a2991d4 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 508
43 UIKit                          0x000000018a2b0e04 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:] + 68
44 TestApp                        0x00000001000bfc7c -[RMSTokenView textFieldDidBeginEditing:] (RMSTokenView.m:463)
45 UIKit                          0x000000018a366aec -[UITextField _becomeFirstResponder] + 564
46 UIKit                          0x000000018a2e5a8c -[UIResponder becomeFirstResponder] + 392
47 UIKit                          0x000000018a2e5e10 -[UIView(Hierarchy) becomeFirstResponder] + 124
48 UIKit                          0x000000018a3654e8 -[UITextField becomeFirstResponder] + 68
49 UIKit                          0x000000018a36653c -[UIView(Hierarchy) deferredBecomeFirstResponder] + 72
50 UIKit                          0x000000018a260560 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 200
51 Foundation                     0x000000018690e368 -[NSISEngine withBehaviors:performModifications:] + 176
52 UIKit                          0x000000018a2603e8 -[UIView(Hierarchy) _postMovedFromSuperview:] + 452
53 UIKit                          0x000000018a26bea4 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1724
54 UIKit                          0x000000018a44ebe0 __53-[_UINavigationParallaxTransition animateTransition:]_block_invoke + 1436
55 UIKit                          0x000000018a27277c +[UIView(Animation) performWithoutAnimation:] + 88
56 UIKit                          0x000000018a44e3a4 -[_UINavigationParallaxTransition animateTransition:] + 856
57 UIKit                          0x000000018a408278 -[UINavigationController _startCustomTransition:] + 3036
58 UIKit                          0x000000018a318f40 -[UINavigationController _startDeferredTransitionIfNeeded:] + 468
59 UIKit                          0x000000018a318d0c -[UINavigationController __viewWillLayoutSubviews] + 56
60 UIKit                          0x000000018a318c8c -[UILayoutContainerView layoutSubviews] + 200
61 UIKit                          0x000000018a261874 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 572
62 QuartzCore                     0x0000000189bb9d58 -[CALayer layoutSublayers] + 168
63 QuartzCore                     0x0000000189bb4944 CA::Layer::layout_if_needed(CA::Transaction*) + 320
64 QuartzCore                     0x0000000189bb47e8 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
65 QuartzCore                     0x0000000189bb3fe8 CA::Context::commit_transaction(CA::Transaction*) + 276
66 QuartzCore                     0x0000000189bb3d6c CA::Transaction::commit() + 436
67 QuartzCore                     0x0000000189bad79c CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 80
68 CoreFoundation                 0x0000000185a9a388 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
69 CoreFoundation                 0x0000000185a97314 __CFRunLoopDoObservers + 360
70 CoreFoundation                 0x0000000185a976f4 __CFRunLoopRun + 836
71 CoreFoundation                 0x00000001859c5664 CFRunLoopRunSpecific + 396
72 GraphicsServices               0x000000018ead35a4 GSEventRunModal + 168
73 UIKit                          0x000000018a2ca4f8 UIApplicationMain + 1488
74 TestApp                        0x000000010000ab54 main (main.m:17)
75 libdyld.dylib                  0x0000000196ba2a08 start + 4

**Comment by rcdilorenzo** [comment]
Give this a try with the updates and feel free to open another issue if this crash persists.
